mojoaxel/awesome-regression-testing

- README.md
> Add some new reference

- README.md
Blog post and github repo about visual regression testing using Chromeless, Jest and AWS Lambda
> Update README.md: blogpost Chromeless

- README.md
Add [reg-suit](https://github.com/reg-viz/reg-suit) to "Tools and frameworks"
> add reg-suit to "Tools and frameworks"

- README.md
Added Differencify to Tools and frameworks section and a blog post for how to use the tool
> Added Differencify

- README.md
Added VisWiz.io to the list of Online services.
> Added VisWiz.io

- README.md
I have been working on a framework called Muppeteer, which uses Mocha, Puppeteer and a visual regression engine for checking component differences. 
https://github.com/HuddleEng/Muppeteer
> Add Muppeteer framework

- README.md
Added a new tutorial on how to setup visual tests using Puppeteer, Jest and VisWiz.io.
> Added VisWiz tutorial with Puppeteer and Jest

- README.md
Add ember-visual-test to the Tools and frameworks section.
> Add ember-visual-test

- README.md
I have added Nikhil Verma's talk "Visual Regression Testing - from a tool to a process" available on Speakerdeck: https://speakerdeck.com/nikhilverma/visual-regression-testing-from-a-tool-to-a-process
> Added Visual Verma's talk about VRT in Badoo

- README.md
Test-oriented browser automation library based on Puppeteer
https://github.com/angrykoala/wendigo
> Added Wendigo

- README.md
Just found this list and thought I'd add what we built for our visual regression testing needs :)
> Add jest-puppeteer-react

- README.md
Still in very early stage but should be mature enough to mention it here.
> add test-crawler

- README.md
- add basset to tools and frameworks
> add basset

- README.md
I am a founder of Backtrac. Project has been stopped. Instead, we have launched Diffy. Please replace the link.
> Diffy instead of Backtrac

- README.md
> chore: wdio-visual-regression

- README.md
Adding https://github.com/microsoft/playwright from Microsoft
> Add Playwright to Tools and frameworks

- README.md
https://web.archive.org/web/20190511225151/http://mogotest.com/ is a
mixture between web testing and mattress-related stuff
> mogotest.com is now a mattress-related business

- README.md
Adding theheadless.dev under new section "Guides" as Puppeteer and Playwright are listed above.
> Add theheadlessdev

- README.md
Removed a duplicate PhantomFlow item in the deprecated list
> Removed duplicate in README

- README.md
Reverts mojoaxel/awesome-regression-testing#60
This video has nothing to do with regression testing
> Revert "Add book and video by Matthew Rudd"

- README.md
This reverts commit d09ad3dc1533bad93ff1b0449fefe50a101e574d.
This book has nothing to do with regression testing
> Revert "Added Regression, a Friendly Guide (#58)"

- README.md
TestingBot provides a free for Open Source account, capable of running visual tests on +3600 browser combinations.
> propose adding TestingBot

- README.md
> add Preflight.com

- README.md
let me know if you have any questions or concerns. thanks!
> added visual regression testing blog post with updated tools in 2022

- README.md
Would be glad to add VRTs to the list!
> Add VRTs WordPress Plugin

- README.md
I've added [Pixeleye](https://pixeleye.io/home) to the list.
Awesome list btw
> Adding Pixeleye

- README.md
The service is called "Argos" and not "Argos-CI".
Also put in top position since it's the best cost/value service in the market.
> Update Argos in list
